export interface Vendor {
  id: string;
  name: string;
  logo: string;
  description: string;
  categories: string[];
  rating: number;
  website: string;
  location: string;
  isVerified?: boolean;
  isTopRated?: boolean;
  isPartner?: boolean;
}

export const vendors: Vendor[] = [
    // Existing Vendors Updated
    {
        id: "ven-elite",
        name: "Elite MedTech",
        logo: "/placeholder/vendor-elitemed.png",
        description: "Premier provider of cutting-edge medical equipment and technology solutions for clinics.",
        categories: ["HRT & Hormone Diagnostics", "IV Therapy Equipment", "Supplements & Wellness"],
        rating: 4.8,
        website: "https://elitemedtech.dev",
        location: "San Diego, CA",
        isVerified: true,
        isTopRated: true,
    },
    {
        id: "ven-bioregen",
        name: "BioRegen Labs",
        logo: "/placeholder/vendor-bioregen.png",
        description: "Innovations in regenerative medicine, PRP systems, and high-potency supplements.",
        categories: ["Regenerative Devices", "IV Therapy Equipment", "Supplements & Wellness"],
        rating: 4.6,
        website: "https://bioregenlabs.dev",
        location: "Boston, MA",
        isVerified: true,
    },
    {
        id: "ven-cryomax",
        name: "CryoMax Systems",
        logo: "/placeholder/vendor-cryomax.png",
        description: "The gold standard in whole-body and localized cryotherapy recovery systems.",
        categories: ["Cryotherapy & Recovery", "Regenerative Devices"],
        rating: 4.9,
        website: "https://cryomaxsystems.dev",
        location: "Denver, CO",
        isVerified: true,
        isTopRated: true,
    },
    {
        id: "ven-novalyte",
        name: "Novalyte™ AI Software",
        logo: "/placeholder/vendor-novalyte.png",
        description: "Integrated EMR, PM, and AI-powered tools for modern men's health clinics.",
        categories: ["Clinic Software Tools"],
        rating: 5.0,
        website: "https://novalyte.ai",
        location: "Palo Alto, CA",
        isVerified: true,
        isPartner: true,
        isTopRated: true,
    },
    
    // New Vendors with complete data
    {
        id: "ven-titan",
        name: "Titan Labs",
        logo: "/placeholder/vendor-titanlabs.png",
        description: "Pharmaceutical-grade supplements and performance nutrition for peak male vitality.",
        categories: ["Supplements & Wellness", "HRT & Hormone Diagnostics"],
        rating: 4.7,
        website: "https://titanlabs.dev",
        location: "Austin, TX",
        isVerified: true,
    },
    {
        id: "ven-apex",
        name: "Apex Performance Gear",
        logo: "/placeholder/vendor-apex.png",
        description: "High-performance fitness equipment and advanced recovery tools designed for professional athletes and peak performers.",
        categories: ["Cryotherapy & Recovery", "Regenerative Devices"],
        rating: 4.5,
        website: "https://apexgear.dev",
        location: "Miami, FL",
        isVerified: true,
    },
    {
        id: "ven-biored",
        name: "BioRedTech",
        logo: "/placeholder/vendor-biored.png",
        description: "Cutting-edge red-light therapy and biohacking devices for cellular optimization and recovery.",
        categories: ["Regenerative Devices"],
        rating: 4.8,
        website: "https://bioredtech.dev",
        location: "Seattle, WA",
        isVerified: true,
    },
    {
        id: "ven-groomforge",
        name: "GroomForge",
        logo: "/placeholder/vendor-groomforge.png",
        description: "Premium, science-backed grooming essentials engineered for men, focusing on skin health and anti-aging.",
        categories: ["Supplements & Wellness"],
        rating: 4.4,
        website: "https://groomforge.dev",
        location: "Los Angeles, CA",
    },
    {
        id: "ven-alpha",
        name: "Alpha Clinic Partners",
        logo: "/placeholder/vendor-alpha.png",
        description: "Specialized logistics and support for TRT and hormone replacement therapies, ensuring clinic efficiency.",
        categories: ["HRT & Hormone Diagnostics"],
        rating: 4.9,
        website: "https://alphaclinic.dev",
        location: "Nashville, TN",
        isVerified: true,
        isPartner: true,
    },
    {
        id: "ven-vitalscan",
        name: "VitalScan Diagnostics",
        logo: "/placeholder/vendor-vitalscan.png",
        description: "Convenient at-home test kits for hormones, lipids, and metabolic markers, with clinic integration.",
        categories: ["HRT & Hormone Diagnostics"],
        rating: 4.6,
        website: "https://vitalscan.dev",
        location: "Salt Lake City, UT",
        isVerified: true,
    },
    {
        id: "ven-ironwave",
        name: "IronWave Fitness Co.",
        logo: "/placeholder/vendor-ironwave.png",
        description: "Professional-grade strength and conditioning equipment for serious results, trusted by commercial gyms.",
        categories: ["Regenerative Devices"],
        rating: 4.7,
        website: "https://ironwave.dev",
        location: "Columbus, OH",
    },
    {
        id: "ven-revivex",
        name: "Revivex Wellness",
        logo: "/placeholder/vendor-revivex.png",
        description: "Advanced recovery tools, longevity protocols, and wellness optimization devices for modern clinics.",
        categories: ["Cryotherapy & Recovery", "Regenerative Devices"],
        rating: 4.8,
        website: "https://revivex.dev",
        location: "Phoenix, AZ",
        isTopRated: true,
        isVerified: true,
    },
    {
        id: "ven-primemen",
        name: "PrimeMen Essentials",
        logo: "/placeholder/vendor-primemen.png",
        description: "Discreet, effective solutions for enhancing male sexual health, confidence, and libido, developed by urologists.",
        categories: ["Supplements & Wellness"],
        rating: 4.5,
        website: "https://primemen.dev",
        location: "Chicago, IL",
        isVerified: true,
    },
    {
        id: "ven-novahair",
        name: "NovaHair Systems",
        logo: "/placeholder/vendor-novahair.png",
        description: "Clinically proven, non-invasive hair growth solutions and systems designed to restore hair density and confidence in men.",
        categories: ["Supplements & Wellness"],
        rating: 4.3,
        website: "https://novahair.dev",
        location: "New York, NY",
    },
];
